apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
#  type: ExternalName
#  externalName: myminio-hl.minio1.svc.cluster.local
